### ISSUE TITLE
The weights are no longer available from the URL

### ISSUE THREAD

**Issue by blacklightpy** [xAlpharax/neural-art#1]
The server seems to be down right now.
I also tried looking for VGG19 weights for PyTorch, and used [this one](https://download.pytorch.org/models/vgg19-dcbb9e9d.pth) specifically, which was from [here](https://pytorch.org/vision/master/_modules/torchvision/models/vgg.html#VGG19_Weights).

But that didn't work, and I got this error:

```
Traceback (most recent call last):
  File "/home/ubuntu/alphara/neural-art/neuralart.py", line 182, in <module>
    vgg.load_state_dict(torch.load(model_path))
  File "/home/ubuntu/alphara/neural-art/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VGG:
        Missing key(s) in state_dict: "conv1_1.weight", "conv1_1.bias", "conv1_2.weight", "conv1_2.bias", "conv2_1.weight", "conv2_1.bias", "conv2_2.weight", "conv2_2.bias", "conv3_1.weight", "conv3_1.bias", "conv3_2.weight", "conv3_2.bias", "conv3_3.weight", "conv3_3.bias", "conv3_4.weight", "conv3_4.bias", "conv4_1.weight", "conv4_1.bias", "conv4_2.weight", "conv4_2.bias", "conv4_3.weight", "conv4_3.bias", "conv4_4.weight", "conv4_4.bias", "conv5_1.weight", "conv5_1.bias", "conv5_2.weight", "conv5_2.bias", "conv5_3.weight", "conv5_3.bias", "conv5_4.weight", "conv5_4.bias".
        Unexpected key(s) in state_dict: "features.0.weight", "features.0.bias", "features.2.weight", "features.2.bias", "features.5.weight", "features.5.bias", "features.7.weight", "features.7.bias", "features.10.weight", "features.10.bias", "features.12.weight", "features.12.bias", "features.14.weight", "features.14.bias", "features.16.weight", "features.16.bias", "features.19.weight", "features.19.bias", "features.21.weight", "features.21.bias", "features.23.weight", "features.23.bias", "features.25.weight", "features.25.bias", "features.28.weight", "features.28.bias", "features.30.weight", "features.30.bias", "features.32.weight", "features.32.bias", "features.34.weight", "features.34.bias", "classifier.0.weight", "classifier.0.bias", "classifier.3.weight", "classifier.3.bias", "classifier.6.weight", "classifier.6.bias".
```

I'm not familiar with this model, but most of the tutorials I could find were for Tensorflow and not PyTorch. So I suppose that's why you named the weights vgg_conv_weights.pth?

I also saw [here](https://datascience.stackexchange.com/questions/56944/how-to-convert-keras-h5-to-pytorch-pth-format) on StackExchange that it is not recommended to convert weights from TF to PyTorch.

> Then, your PyTorch model has the same architecture and weights as the Keras model and **might** behave in the same way.

**Comment by xAlpharax** [comment]
Thanks for noticing! I should just place the weights file in a shared cloud storage folder, the easiest would be drive.

**Comment by xAlpharax** [comment]
Try this: https://drive.google.com/file/d/1Pfh-dHvCdhn97MpLT0_I6QAAzvejqs1i/

**Comment by xAlpharax** [comment]
@blacklightpy Fixed the readme and the automatic downloader from `neuralart.py` in the latest commit [#d0fe889](https://github.com/xAlpharax/neural-art/commit/d0fe8897cd6de445ea76d0105e98ffc8215ae29d)

**Comment by blacklightpy** [comment]
This one works, but it's not possible to wget Drive links afaik. So I had to upload it manually to the VPS.

**Comment by xAlpharax** [comment]
@blacklightpy Have just adjusted the link to: https://files.catbox.moe/wcao20.pth and this seems to be a permanent file upload, so I changed the `README.md` and the automatic downloader inside of `neuralart.py`.
